### ISSUE TITLE
Addressing SQL Injection Vulnerabilities with Raw Methods

### ISSUE THREAD

**Issue by craigfrancis** [canvural/larastan-strict-rules#153]
Ref the suggestion to Laravel core for [Addressing SQL Injection Vulnerabilities with Raw Methods](https://github.com/laravel/framework/discussions/47257).

I'm happy to create a PR, where I've created this issue to [discuss the implementation](https://twitter.com/can__vural/status/1666452691415973890).

I note that you're currently using Rules, but this one might be easier to implement with [Stubs](https://phpstan.org/user-guide/stub-files); if so, I assume new folders `/src/Stubs/` and `/tests/Stubs/`?

Also, I might need some guidance on how you would like to _conditionally_ include these Stubs... I've only done this bit once before, using a [StubFilesExtension](https://github.com/phpstan/phpstan-src/blob/1.11.x/src/PhpDoc/StubFilesExtension.php) class to conditionally `getFiles()`.

**Comment by canvural** [comment]
Hi,

I thought about this today again. And there is a problem. PHPStan does not support stub merging or overriding. And since Larastan already [provides](https://github.com/nunomaduro/larastan/blob/master/stubs/QueryBuilder.stub) stubs for query builder, we can't have new stubs here. So this feature needs to go to Larastan itself.

About implementation, yeah Larastan already has a StubFilesExtension, so we need to add a new value to config, and if it is `true`, in the extension we include the folder with the stubs we want.

A side note, Larastan supports both Laravel 9 and 10. And in Laravel 10 some method definitions changed in query builder to accept `\Illuminate\Contracts\Database\Query\Expression` instead of `\Illuminate\Database\Query\Expression`. There is already an issue about it: https://github.com/nunomaduro/larastan/issues/1547 So if you want to use this typehint, then we need to also check the Laravel version and include the correct stubs for that.

I can also help with the implementation if you need any 👍🏽 And thanks in advance! I believe this will be very useful! Excited to see how it will come along 🤩
